# Generated by Django 4.1.3 on 2022-11-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0004_alter_empresa_logo_vagas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="empresa",
            old_name="caracteristica_Empresa",
            new_name="caracteristica_empresa",
        ),
        migrations.AlterField(
            model_name="vagas",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="empresa.empresa",
            ),
        ),
    ]
