# Generated by Django 4.1.3 on 2022-11-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "empresa",
            "0005_rename_caracteristica_empresa_empresa_caracteristica_empresa_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vagas",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
